### ISSUE TITLE
Cloudfront fails to purge individual URIs

### ISSUE THREAD

**Issue by mattstein** [putyourlightson/craft-blitz-cloudfront#1]
When attempting to invalidate Cloudfront caches, only `purgeAll()` is working with its request for `/*`. Attempting to invalidate an individual URI with the `purgeUris()` method fails because the entire hostname is included and Cloudfront discards the request without logging it. 

This means subsequent edits to a published entry fail to clear the Cloudfront cache and the page appears to get “stuck” on the front end.

Using a root-relative URI, specifically with the forward slash, fixes the issue:

- ☠ `https://foo.dev/my-test-entry` 
- ☠`my-test-entry` (directly from `$siteUris`)
- 👍`/my-test-entry`

Confirmed by replacing [this line](https://github.com/putyourlightson/craft-blitz-cloudfront/blob/v2/src/CloudFrontPurger.php#L143) with a quick test:

```php
$uris = [];

foreach ($siteUris as $uri) {
    $uris[] = '/' . $uri->uri;
}

$this->_sendRequest($uris);
```

---

- Blitz 3.5.2
- Blitz Cloudfront purger 2.0.2
- Craft 3.4.10.1

**Comment by bencroker** [comment]
Thanks Matt, fixed in https://github.com/putyourlightson/craft-blitz-cloudfront/commit/9a7d2df60fd181670b11402f831116fed86e8b89 and released in 2.0.3.
