### ISSUE TITLE
Reference to CloudFlare instead of CloudFront on the distributionId instructions label

### ISSUE THREAD

**Issue by Mmasson-01** [putyourlightson/craft-blitz-cloudfront#14]
### Bug Report

The instruction of the field `distributionId` is refering to CloudFlare instead of CloudFront

Current instruction label:

instructions: 'The ID of the CloudFlare distribution that should be purged.'|t('blitz-cloudfront'),

Desired instruction label:

instructions: 'The ID of the CloudFront distribution that should be purged.'|t('blitz-cloudfront'),

### Plugin Version

5.1.2

### Craft CMS Version

^5.0.0

### PHP Version

8.2

**Comment by bencroker** [comment]
Good catch! Fixed in https://github.com/putyourlightson/craft-blitz-cloudfront/commit/c32546caa2045d45b63244a016804134396d0303 for the next release.
