### ISSUE TITLE
Distribution id cannot be set to an env variable

### ISSUE THREAD

**Issue by goraxan** [putyourlightson/craft-blitz-cloudfront#2]
Even though in the settings screen everything indicates the distribution id can be set to an environment variable, it is not supported in the plugin. It should be handled like the apiKey/apiSecret parameters.

https://github.com/putyourlightson/craft-blitz-cloudfront/blob/v2/src/CloudFrontPurger.php#L224

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-blitz-cloudfront/commit/170225b5d2009399226ee6a45def4b87eeabdbc8 and released in version 2.0.4.
