### ISSUE TITLE
Support IAM roles in EC2 instances

### ISSUE THREAD

**Issue by goraxan** [putyourlightson/craft-blitz-cloudfront#3]
If the AWS apiKey and apiSecret are empty after being read by the parseEnv method, assume we are running on EC2 and we have an IAM role assigned and don't assign any credentials to the AWS CloudFrontClient.

An example: https://github.com/craftcms/aws-s3/blob/9100ef560f20df6d84dcaa176d2d5b4dabed13f7/src/Volume.php#L432

**Comment by bencroker** [comment]
Thanks, done in https://github.com/putyourlightson/craft-blitz-cloudfront/commit/170225b5d2009399226ee6a45def4b87eeabdbc8 and released in version 2.0.4.
